### PR TITLE
Richtext fixes

### PR DESCRIPTION
**Pull request by mnoskov**

### CODE REVIEW

**Comment by fourroses666** [comment]
Coincidental I was looking for richtext for multiTV and saw this pull request.

I haven't used Richtext before so don't know about the fixes, but tested this pull and it worked _(on an install version 1.2.1)_

Just needed to use these settings;
```
        'richtext' => array(
        'caption' => 'Tekstveld',
        'type' => 'richtext',
        'theme' => 'mini'
    )
```

Would be cool if the icons could be on 1 row and Insert Link could be added to the richtext mini theme.

**Comment by mnoskov** [comment]
It's not multiTV issue, theme "mini" can be modified here - https://github.com/evolution-cms/evolution/blob/develop/assets/plugins/tinymce4/theme/theme.tinymce4.mini.inc.php

**Comment by mnoskov** [comment]
I agree, minitheme can be more mini, in one row

**Comment by fourroses666** [comment]
Thanks for pointing the location. 👍 

And the html icon <> when you paste wrong html.
At default these icons added would be great.

**Pull request merged**
